[toolchain]
# TODO: bump nightly and wasmer once https://github.com/wasmerio/wasmer/issues/5610 is fixed.
channel = "nightly-2025-08-15"
# channel = "1.89"
# channel = "1.91"
components = [ "clippy", "rustfmt", "llvm-tools" ]
targets = [ "wasm32v1-none" ]
